name: "Publish to Valar"
on:
  push:
    branches:    
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: valar/action@v1
      
    - name: valar push
      run: |
        valar --api-token ${{ secrets.VALAR_TOKEN }} --api-endpoint https://api.valar.dev push
